Module2 task1
htmlacademy-adaptive/845199-pink-23 pull request #2
Opened 2021-07-25 19:18 UTC by dopamine-s

2021-07-26 15:59 UTC, wrgraff requested changes
Лучше абсолютно пустых страниц не создавать, так как они будут не валидны.

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +      <a class="page-header__logo-name logo-name" href="index.html">
Обрати внимание на то, как логотип меняется при переходе на планшетную и десктопную версии.
`logo-name` подходит не слишком хорошо, так как имя тут только в одной из версий.

Логотипы в хэдере и футере ведут себя похожим образом.
Пока не усложняй и используй один и тот же БЭМ-блок, например просто`logo` для хэдера и футера.
Они могут различаться тем, что картинки в них будут разные, а БЭМ-блок останется один и тот же.

Ты пока можешь не понимать, как именно получится настроить логотипы с таким поведением, но тебе и не нужно: всему свое время

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +        <img class="logo-name__header-image" src="img/logo-name-mobile-header.svg" width="74" height="23" alt="Мобильное приложение «Pink»" style="background-color: black;">
Смотри, формально это не ошибка по БЭМ, но с точки зрения сути БЭМа получается ерунда.
У тебя должен быть блок независимый, а его элементы должны принадлежать только ему без оглядки на окружение.
А у тебя элемент называется `logo-name__header-image`, ты его привязываешь к хэдеру. Звучит как зависимость от местоположения.

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +        <img class="logo-name__header-image" src="img/logo-name-mobile-header.svg" width="74" height="23" alt="Мобильное приложение «Pink»" style="background-color: black;">
Не нужно инлайнить стили
```suggestion
        <img class="logo-name__header-image" src="img/logo-name-mobile-header.svg" width="74" height="23" alt="Мобильное приложение «Pink»">
```

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +        <div class="main-nav_wrapper">
Похоже, не хватает одного подчеркивания.
Пользуйся [генератором дерева от Йоксель](https://yoksel.github.io/html-tree/), чтобы чисто технические ошибки/опечатки убирать сразу

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +        <div class="main-nav_wrapper">
Кстати, а можешь обосновать с какой именно целью тут обертка используется?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          <button class="app__button button">Скачать приложение</button>
Как именно должна сработать кнопка в данном случае?
Посмотри как описана логика работы [в ТЗ](https://up.htmlacademy.ru/adaptive/23/project/pink#pink-4-2)

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +                <img class="platform-list__item-image" src="img/apple-logo.svg" width="47" height="56" alt="Логотип «Apple»" style="background-color: black;"/>
А почему `platform-list__link` — норм, а вместо простого `platform-list__image` используется `platform-list__item-image`?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +                <img class="platform-list__item-image" src="img/apple-logo.svg" width="47" height="56" alt="Логотип «Apple»" style="background-color: black;"/>
Картинка тут конечно не особо контентная, а больше декоративная.
Хотелось бы увидеть скрытый текст и модификатор для картинок

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          <h2 class="visually-hidden app-functions__title">
С какой целью к классу `visually-hidden` примиксован класс элемента?
`visually-hidden` полностью скрывает элемент, выключая его оформление. Какое дополнительное оформление ему может понадобиться?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          <h2 class="visually-hidden app-functions__title">
Кроме того, до этого момента ты писал всегда сперва класс элемента, а потом блок.
Придерживайся одного порядка классов

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          </dl>
Список определений... Ну такое, ооооочень с натяжкой.
Намного проще сделать это списком, который содержит заголовок + описание

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +                </p>
Почему `reviews__author-info` и `reviews__author-name`, но `reviews__text`?
"текст" даже вложен в "инфо". Логика как-то посыпалась чутка.

И возникает вообще вопрос: зачем нужна обертка `reviews__author-info`, если внутри отзыва по сути имя и параграф: всего пара элементов.
Если ты закладываешься на то, что потом там будет "25 лет, водитель трамвая", то размечай и этот текст тоже сразу, чтобы не путаться.

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +            <button class="slider__toggle" type="button">3</button>
1, 2, 3 — так себе описание

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +            <button class="slider__toggle" type="button">3</button>
Почему бы сразу не сделать скрытым текст?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          <p class="reviews__toggles slider__toggles">
Откуда лишний шаг вложенности?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          <div class="rates__list">
`rates__list` вообще не очень понятно с какой целью тут

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +              </tr>
Кажется, этот блок вообще можно выделить в `<thead>`, а остальное, соответственно, в `<tbody>`

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +                <td class="rates__advantage">Розовый фильтр</td>
Как по 3 описаниям "розовый фильтр" человек без зрения поймет какой из них активен для тарифа, а какой — нет?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +                <td class="rates__advantage rates__advantage--current">Розовый фильтр</td>
Смотри на таблицу на соседних экранах:
![изображение](https://user-images.githubusercontent.com/37917037/127018336-ed1e98d2-36cb-478d-baf2-5de9921b5d91.png)

Активен не только средний пункт в каждом случае

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          </p>
Мы когда обсуждали как поступать со слайдером, я предлагал избавиться от блока `slider` и оставить блок для кнопок, потому что они повторяются.

В итоге вышло наоборот:
Ты оставил блок `slider`, замиксовав его к отзывам и сделал разные элементы для кнопок (`rates__toggles` и `slider__toggles`).

Микс со слайдером тебе ничего не дает: все стили, которые ты захочешь повесить на него, можно повесить на блок отзывов. А оформление одинаковых кнопок тебе нужно будет приписать дважды в разных местах.

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +                  <p class="rates__item--name">База</p>
Класс как у модификатора

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +        </h2>
Если делаешь заголовок, делай его для секции.
И ставь в начале, а не после параграфа

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +        <p class="page-footer__subject footer-subject">
Зачем для всего лишь небольшого текста `footer-subject` целый блок?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +              </a>
Откуда вложенность тут лишняя

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +              <a class="contacts__mail contacts__link" href="mailto:mail@htmlacademy.ru">
Если ты постоянно миксуешь к одному и тому же элементу (`contacts__link` в данном случае) другой элемент (то `contacts__mail`, то `contacts__phone`), то вероятно тебе на самом деле нужен модификатор.

Но в данном случае я вообще не очень понимаю зачем он может быть нужен, потому что все элементы выглядят одинаково

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +        <div class=page-footer__logo>
С каких это пор у нас классы без кавычек пошли?

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          </a>
Во-первых, не надо делать 2 элемента, оставь один логотип.
Сверху одна картинка будет, тут другая. Вот и все.

Но даже если бы он состоял из двух картинок, они бы все равно были внутри только одной ссылки. Делить интерактивный элемент — это уже криминал

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +                <img src="img/twitter.svg" width="18" height="14" alt="twitter"/>
Не ставь картинку, раз уж ставишь модификатор и скрытый текст.
А то что за ядерное сочетание

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +              <img src="img/facebook.svg" width="9" height="18" alt="facebook"/>
Форматирование поехало

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +            <img class="academy-social-logo" src="img/html_academy_social_logo.svg" width="27" height="34" alt="логотип «html academy»">
Не надо дублировать картинку в разметке скрытым текстом. Или одно или другое, не перегружай.

2021-07-26 15:59 UTC, wrgraff commented on source/index.html
> +          <a class="copyright__link visually-hidden" href="https://htmlacademy.ru/intensive/adaptive">
Повесив на ссылку класс `visually-hidden` ты сделал ее и все ее содержимое невидимым

2021-07-26 17:45 UTC, dopamine-s commented on source/index.html
> +          <a class="copyright__link visually-hidden" href="https://htmlacademy.ru/intensive/adaptive">
Убрал

2021-07-26 17:47 UTC, dopamine-s commented on source/index.html
> +            <img class="academy-social-logo" src="img/html_academy_social_logo.svg" width="27" height="34" alt="логотип «html academy»">
Убрал скрытый текст,

2021-07-26 17:47 UTC, dopamine-s commented on source/index.html
> +              <img src="img/facebook.svg" width="9" height="18" alt="facebook"/>
Поправил

2021-07-26 17:53 UTC, dopamine-s commented on source/img/html_academy_social_logo.svg
> +</svg>
Исправил

2021-07-27 20:03 UTC, dopamine-s commented on source/index.html
> +      <a class="page-header__logo-name logo-name" href="index.html">
будет просто logo

2021-07-27 20:04 UTC, dopamine-s commented on source/index.html
> +        <img class="logo-name__header-image" src="img/logo-name-mobile-header.svg" width="74" height="23" alt="Мобильное приложение «Pink»" style="background-color: black;">
Просто без этого логотипа вообще не видно. Он же белый. 
Убрал

2021-07-27 20:10 UTC, dopamine-s commented on source/index.html
> +        <div class="main-nav_wrapper">
Взят прицел на возможное добавление второй навигации для логина. Вдруг понадобится? Ну нет, так нет. Уберем обертку. Логина в макете нет.

2021-07-27 20:15 UTC, dopamine-s commented on source/index.html
> +          <button class="app__button button">Скачать приложение</button>
Поставил ссылку 
https://www.apple.com/ru/app-store/

2021-07-27 20:16 UTC, dopamine-s commented on source/index.html
> +                <img class="platform-list__item-image" src="img/apple-logo.svg" width="47" height="56" alt="Логотип «Apple»" style="background-color: black;"/>
> А почему `platform-list__link` — норм, а вместо простого `platform-list__image` используется `platform-list__item-image`?
ОК, поменял

2021-07-27 20:34 UTC, dopamine-s commented on source/index.html
> +                <img class="platform-list__item-image" src="img/apple-logo.svg" width="47" height="56" alt="Логотип «Apple»" style="background-color: black;"/>
Меняю

2021-07-27 20:46 UTC, dopamine-s commented on source/index.html
> +          </dl>
Все-таки мне кажется это верным. Функция и ее расшифровка. Четкая последовательность. Суть и детали.

2021-07-27 21:00 UTC, dopamine-s commented on source/index.html
> +                </p>
Обертку убрал. Название поправил

2021-07-27 21:04 UTC, dopamine-s commented on source/index.html
> +            <button class="slider__toggle" type="button">3</button>
Поменял

2021-07-27 21:11 UTC, dopamine-s commented on source/index.html
> +          <p class="reviews__toggles slider__toggles">
Кнопки выбились из Дива. Они относятся к слайдеру, должны быть внутри.

2021-07-27 21:13 UTC, dopamine-s commented on source/index.html
> +          <div class="rates__list">
Согласен, глупо. Всё от спешки, времени вечно не хватает.

2021-07-27 21:50 UTC, dopamine-s commented on source/index.html
> +              </tr>
ok

2021-07-28 05:19 UTC, dopamine-s commented on source/index.html
> +        </h2>
Поправил

2021-07-28 16:41 UTC, dopamine-s commented on source/index.html
> +                <td class="rates__advantage rates__advantage--current">Розовый фильтр</td>
Вроде бы понял и поправил

2021-07-28 16:48 UTC, dopamine-s commented on source/index.html
> +          </p>
Я кажется понял идею, но не понимаю, почему нужно избавляться именно от слайдера. Ведь именно rates__toggles или reviews__toggles будут разными. А слайдер можно сделать общим. Попробую

2021-07-28 16:56 UTC, dopamine-s commented on source/index.html
> +                  <p class="rates__item--name">База</p>
Убрал

2021-07-28 16:58 UTC, dopamine-s commented on source/index.html
> +        <p class="page-footer__subject footer-subject">
Оставил только  page-footer__subject

2021-07-28 17:12 UTC, dopamine-s commented on source/index.html
> +              </a>
Убрал

2021-07-28 17:12 UTC, dopamine-s commented on source/index.html
> +              <a class="contacts__mail contacts__link" href="mailto:mail@htmlacademy.ru">
Убрал

2021-07-28 17:15 UTC, dopamine-s commented on source/index.html
> +          </a>
понял

2021-07-28 17:17 UTC, dopamine-s commented on source/index.html
> +                <img src="img/twitter.svg" width="18" height="14" alt="twitter"/>
ок

2021-07-28 22:03 UTC, wrgraff commented on source/index.html
> +        <img class="logo-name__header-image" src="img/logo-name-mobile-header.svg" width="74" height="23" alt="Мобильное приложение «Pink»" style="background-color: black;">
Да и плевать, стили начнем делать и все будет видно сразу

2021-07-28 22:05 UTC, wrgraff commented on source/index.html
> +        <div class="main-nav_wrapper">
Откуда тут логин?
Не надо вообще загадывать на будущее и предугадывать то, что может случиться.
Подстелишь себе соломку там, куда точно не свалишься

2021-07-28 22:11 UTC, wrgraff commented on source/index.html
> +              <a class="platform-list__link link--apple" href="#">
Косяк. ты ставишь модификатор для блока `link`. А его не существует:
![изображение](https://user-images.githubusercontent.com/37917037/127402605-da913b3f-3e91-48bb-84e4-8be78cd197d0.png)
Это ошибка по БЭМу

2021-07-28 22:11 UTC, wrgraff commented on source/index.html
> +          </dl>
Учитывая, что скринридер умеет навигировать по заголовкам, список преимуществ с заголовками он бы прочитал лучше, чем список определений.

2021-07-28 22:15 UTC, wrgraff commented on source/index.html
> +              </cite>
А должность и возраст можно и заранее сделать.
И вообще, смотри на другие версии макета: планшетную и десктоп. Там видно некоторые новые элементы и поведение существующих

2021-07-28 22:15 UTC, wrgraff commented on source/index.html
> +          <div class="rates__list">
А зачем оставил )

2021-07-28 22:18 UTC, wrgraff commented on source/index.html
> +                  <td class="rates__advantage"><span class="visually-hidden">Вид преимущества</span>Розовый фильтр<span class="visually-hidden">включено в тариф</span></td>
Не помешали бы модификаторы для отметки того, где у нас галочка, а где красный крест

2021-07-28 22:18 UTC, wrgraff commented on source/index.html
> +                  <td class="rates__advantage"><span class="visually-hidden">Вид преимущества</span>Смайлики<span class="visually-hidden">включено в тариф</span></td>
А еще не помешало бы вложенные теги разбить по строкам.
Смотри, это же реально каша какая-то:
![изображение](https://user-images.githubusercontent.com/37917037/127403388-e75693e4-112d-4532-b5ab-e463f027c9c0.png)

Не разобрать ничего

2021-07-28 22:18 UTC, wrgraff commented on source/index.html
> +                <td class="rates__advantage rates__advantage--current">Розовый фильтр</td>
Вижу только что убрал классы активности вообще

2021-07-28 22:20 UTC, wrgraff commented on source/index.html
> +          </p>
Потому что кнопки и там и там одинаковые.
Подскажи, в чем именно ты видишь разницу между ними:
![изображение](https://user-images.githubusercontent.com/37917037/127403621-24579d39-8d29-41ac-84c6-368aee4e2aeb.png)
![изображение](https://user-images.githubusercontent.com/37917037/127403640-496d55c9-305d-4001-af0e-8ded1e49336d.png)

А у таблицы слайдов нет вообще

2021-07-28 22:22 UTC, wrgraff commented on source/index.html
>          <h2 class="visually-hidden page-footer__title">
Сочетание элемента со скрывающим класслм тут тоже не имеет смысла

2021-07-28 22:22 UTC, wrgraff commented on source/index.html
> +              </a>
Не убрал

2021-07-28 22:23 UTC, wrgraff commented on source/index.html
> +              </a>
Ссылка же не вложена в текст "Звоните"
![изображение](https://user-images.githubusercontent.com/37917037/127403900-169fa062-c087-4519-b1f9-d154ab5b48f9.png)

2021-07-28 22:25 UTC, wrgraff requested changes
Еще есть несколько поправок

2021-07-28 23:02 UTC, dopamine-s commented on source/index.html
> +              <a class="platform-list__link link--apple" href="#">
Поменял

2021-07-28 23:04 UTC, dopamine-s commented on source/index.html
> +              </cite>
Буду иметь в виду. Пока ограничусь необходимым. Опаздываю.

2021-07-28 23:14 UTC, dopamine-s commented on source/index.html
> +                  <td class="rates__advantage"><span class="visually-hidden">Вид преимущества</span>Розовый фильтр<span class="visually-hidden">включено в тариф</span></td>
Сделал

2021-07-28 23:30 UTC, dopamine-s commented on source/index.html
> +                  <td class="rates__advantage"><span class="visually-hidden">Вид преимущества</span>Смайлики<span class="visually-hidden">включено в тариф</span></td>
Поправил

2021-07-28 23:35 UTC, dopamine-s commented on source/index.html
>          <h2 class="visually-hidden page-footer__title">
Оставил только скрытие. Это имеет смысл.

2021-07-29 16:42 UTC, wrgraff commented on source/index.html
> +                Отзыв 1
Сам текст не обязательно выбивать на строку отдельную.
Это уже на любителя.

2021-07-29 16:42 UTC, wrgraff commented on source/index.html
> +                  <td class="rates__advantage rates__advantage--non-active">
Какое-то странное слово...

```suggestion
                  <td class="rates__advantage rates__advantage--inactive">
```

2021-07-29 16:42 UTC, wrgraff commented on source/index.html
>                    <th class="rates__item rates__item--current" scope="col">
Непонятно зачем остался `rates__item--current`

2021-07-29 16:42 UTC, wrgraff commented on source/index.html
> +              </cite>
Непонятно только как то, что ты разметишь элементы не сейчас, а потом, ускорит процесс работы

2021-07-29 16:43 UTC, wrgraff approved these changes

2021-07-29 16:43 UTC, wrgraff commented on source/form.html
> +            </li>
Ну не исправил же форматирование.
И в прошлом ревью я тоже отмечал. Исправь

2021-07-29 16:44 UTC, merged

2021-07-30 02:12 UTC, dopamine-s commented on source/index.html
>                    <th class="rates__item rates__item--current" scope="col">
Убрал

2021-07-30 02:16 UTC, dopamine-s commented on source/index.html
> +                  <td class="rates__advantage rates__advantage--non-active">
поменял