Module2 task2
htmlacademy-adaptive/845199-pink-23 pull request #3
Opened 2021-08-03 17:54 UTC by dopamine-s

2021-08-03 21:38 UTC, wrgraff requested changes
Не так много правок

2021-08-03 21:38 UTC, wrgraff commented on source/catalog.html
> +            <span class="photo__photo-of-the-day">
Какой-то странный класс.
"Фото дня" — это описание фотографии. А этот элемент не является фотографией дня. Такие плашки зовутся лейблами. Описывай именно элемент и то, как он выглядит:
```suggestion
            <span class="photo__label">
```

2021-08-03 21:38 UTC, wrgraff commented on source/catalog.html
> +              <a class="photo__link-likes link-likes" href="#">
Ну, тут может быть немного перегиб с тем, что это ссылка. Не будут лайки работать — не страшно.
Но мне нравится, как ты счетчик и саму кнопку объединил.

2021-08-03 21:38 UTC, wrgraff commented on source/catalog.html
> +            </h3>
Такого рода заголовки давать смысла особо нет. Заголовки зачем нужны? Понять что за информация, дифференцировать ее. А что ты разного узнаешь, если они одинаковые?
Используй хотя бы варианты попроще и понятнее, типа "Фото Анны", "Фото Левона", и так далее

2021-08-03 21:38 UTC, wrgraff commented on source/catalog.html
> +          Раздел для предварительного редактирования и размещения пользовательских фотографий
Сложно.
Краткость — сестра таланта.
Надо всего лишь обозначить, что это форма для редактирования и размещения фото

2021-08-03 21:38 UTC, wrgraff commented on source/catalog.html
> +          <input class="user-photo__range" type="range" min="1" max="10" id="size" value="8">
Не забывай, что там 3 слайда: по одному для каждого из параметров.
Желательно разметку сразу планировать для всех. А то стилизуешь как есть, а потом придется разметку обновить и переоформить

2021-08-03 21:38 UTC, wrgraff commented on source/catalog.html
> +          <label for="size">
Старайся не плодить названий. У тебя выбрано кадрирование, кадрирование — это `crop`, судя по модификатору. Используй это в id, name и прочих параметрах. так понятнее что чему соответствует.

2021-08-03 23:35 UTC, dopamine-s commented on source/catalog.html
> +          <article class="photo__item photo__item--active">
photo__item--hot

2021-08-03 23:35 UTC, dopamine-s commented on source/catalog.html
> +              </cite>
Исправил. Сделал обертку параграфом

2021-08-03 23:35 UTC, dopamine-s commented on source/catalog.html
> +            <span class="photo__photo-of-the-day">
Хорошо.

2021-08-03 23:35 UTC, dopamine-s commented on source/catalog.html
> +              <a class="photo__link-likes link-likes" href="#">
Ну вот хоть что-то  у меня нормально)

2021-08-03 23:40 UTC, dopamine-s commented on source/catalog.html
> +          Раздел для предварительного редактирования и размещения пользовательских фотографий
Раздел редактирования и размещения фотографий
 
 Короче.

2021-08-03 23:43 UTC, dopamine-s commented on source/catalog.html
> +            </h3>
Дал заголовки по требованию к валидности кода. h3 был нужен для article. 

Сделаю короче, согласен. Раз они вообще нужны.

2021-08-04 00:27 UTC, dopamine-s commented on source/catalog.html
> +          <input class="user-photo__range" type="range" min="1" max="10" id="size" value="8">
ок

2021-08-04 00:29 UTC, dopamine-s commented on source/catalog.html
> +          <label for="size">
Сделал так для всех рэйнджей.

2021-08-04 00:29 UTC, dopamine-s commented on source/form.html
> +                фамилия:
Поправил для всех пунктов

2021-08-04 00:30 UTC, dopamine-s commented on source/form.html
> +            </li>
Пока оставлю, если это не критично.

2021-08-04 00:31 UTC, dopamine-s commented on source/index.html
> +            п</a>
Случайно иногда нажимаю на клавиши)

2021-08-04 00:33 UTC, dopamine-s commented on source/form.html
> +              <label for="iOS">Pink для iOS</label>
Исправил

2021-08-04 09:42 UTC, wrgraff approved these changes

2021-08-04 09:42 UTC, merged