Module3 task1
htmlacademy-adaptive/845199-pink-23 pull request #4
Opened 2021-08-09 23:39 UTC by dopamine-s

2021-08-10 19:18 UTC, wrgraff requested changes
Все хорошо, критичных замечаний буквально полторы штуки

2021-08-10 19:18 UTC, wrgraff commented on source/sass/blocks/photo.scss
> +  height: 36px;
Во-первых, для задания размеров рановато. Не тот раздел, не то задание.
Во-вторых, что, если объем текста изменится? Переполнение тут сразу поломано.

2021-08-10 19:18 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +}
Расписал про эти вложенности и почему они не нужны [в ролике](https://t.me/c/1575054124/2)
Я решил постить ролики в телеграм: там и быстро и качество хорошее. Сделал чисто для нас канал, зайди в него [по инвайту](https://t.me/joinchat/kDI_dkt85pQ0YjI6).

2021-08-10 19:18 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +  color: $gray-dark;
Просто напомню, по умолчанию многие браузеры делают плейсхолдер полупрозрачным

2021-08-10 19:18 UTC, wrgraff commented on source/sass/blocks/form-button.scss
> +  height: 59px;
Сходу убил переполнение.
Оставь лучше как есть, пускай кнопка схлопывается.
Или поставь какие-то `padding`'и, но только не ширину и высоту

2021-08-10 19:18 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  min-height: 55px;
Аналогично лейблу и другой кнопке: лучше пока примерные внутренние отступы

2021-08-10 22:57 UTC, dopamine-s commented on source/sass/blocks/form-group.scss
> +  color: $gray-dark;
ок

2021-08-10 23:41 UTC, dopamine-s commented on source/index.html
> +    <link rel="preload" href="fonts/opensans.woff2" as="font" type="font/woff2" crossorigin>
ок

2021-08-10 23:41 UTC, dopamine-s commented on package.json
> +    "normalize.css": "^8.0.1"
ок

2021-08-11 00:12 UTC, dopamine-s commented on source/index.html
> +          <div class="page-header__inner-wrapper">
В основном из-за фонов. Уберу, если окажется. что они совсем лишние. А пока вроде логично (с точки зрения моей несовершенной логики). Всё используется, даже если очень детализировано. Пока бы оставил. Если есть вариант, как лучше переделать - выслушаю. А так из-за этих классов придется опять все менять.

2021-08-11 00:23 UTC, dopamine-s commented on source/form.html
> +          </div>
поправил

2021-08-11 00:29 UTC, dopamine-s commented on source/index.html
> +            Взгляните на жизнь иначе!
Нет в жизни совершенства. Только попытки приблизиться...

2021-08-11 00:38 UTC, dopamine-s commented on source/sass/global/variables.scss
> +$bg-transparent: rgba(0, 0, 0, 0.3);
Потому что здесь цветов намного меньше. Просто не вижу смысла. Я подумал о той схеме, но там их куда больше.

2021-08-11 00:50 UTC, dopamine-s commented on source/sass/global/variables.scss
> +$gray-dark-transparent-1: rgba(40, 54, 69, 0.1);
Буду иметь в виду.

2021-08-11 00:55 UTC, dopamine-s commented on source/sass/global/variables.scss
> +$bg-white: #ffffff;
Ну а вдруг фоновый белый поменяется на кремовый? 
А текст останется таким же?

2021-08-11 00:57 UTC, dopamine-s commented on source/sass/global/variables.scss
> +$bg-white: #ffffff;
Если это прямо вот сильно не оптимально, поменяю.

2021-08-11 01:43 UTC, dopamine-s commented on source/sass/global/fonts.scss
> +    url("../../fonts/opensanslight.woff") format("woff");
Значит меньше на 1 уровень вложенности

2021-08-11 01:44 UTC, dopamine-s commented on source/sass/blocks/social.scss
> +.social ul {
Не думал, что это прямо вот критично. Буду иметь в виду. В критериях задания это как раз указано нормальным.

2021-08-11 01:44 UTC, dopamine-s commented on source/sass/blocks/rates.scss
> +.rates__table th {
ок

2021-08-11 01:45 UTC, dopamine-s commented on source/sass/blocks/photo.scss
> +  height: 36px;
ок

2021-08-11 01:54 UTC, dopamine-s commented on source/sass/blocks/button.scss
> +  min-height: 55px;
ок

2021-08-11 16:25 UTC, dopamine-s commented on source/sass/blocks/form-button.scss
> +  height: 59px;
ок

2021-08-11 20:11 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +}
OK. Смысл есть.

2021-08-11 20:12 UTC, dopamine-s commented on source/index.html
> +          <div class="page-header__inner-wrapper">
Посмотрел ролик. Ты прав, думаю. хотя зря мы убираем inner-wrapper
Он точно понадобится для выравнивания лого и кнопки

2021-08-11 21:05 UTC, wrgraff approved these changes

2021-08-11 21:05 UTC, merged