Module4 task1
htmlacademy-adaptive/845199-pink-23 pull request #6
Opened 2021-08-20 23:14 UTC by dopamine-s

2021-08-21 15:20 UTC, wrgraff requested changes
Задание гласит следующее:

>     - сверстайте адаптивную сетку крупных блоков главной страницы для всех состояний: мобильного, планшетного и десктопного. Нужно добиться такой же перестройки крупных блоков, как на макетах;
>     - не нужно верстать сетки содержательных и мелких элементов;
>     - не нужно добиваться совпадения высот блоков, достаточно задать блокам минимальную высоту на глаз.

Ты сделал верстку еще и мелких сеток, графики и отчасти декора. Не нужно так делать.
1. Ты допустил кучу ошибок, потому что еще не смотрел материалы и лайвы по соответствующим темам.
2. На задание ушло слишком много времени, хотя эффективнее продвигаться небольшими шагами
3. Мне пришлось убить на проверку пол дня. Во-первых, у меня были другие планы. Во вторых, это пол дня, которые ты мог бы поработать: например, получить ревью и уже внести в него правки к этому моменту. В третьих, для меня это дискомфортно и неудобно, и в следующий раз может оказаться, что на проверку уйдет вообще несколько дней.
4. Ты сейчас получил 57 злобных комментариев, которые негативно скажутся на мотивации, потому что кажется, что это много.
5. мы не сможем детальнее сосредоточиться на крупных сетках, потому что 2/3 ошибок пришли из других разделов.

Кроме того, спешка привела еще к одной ошибке.
Задание разрешает ставить минимальную высоту **для верстки крупных блоков** и **при необходимости**. Ты же наставил минимальную высоту везде, даже айтемам в меню. И не по необходимости, а выстроил в некоторых местах на них сетки.

Вывод такой: не нужно спешить.
Делай то, что требуется в задании.

2021-08-21 15:20 UTC, wrgraff commented on source/index.html
>                  </tr>
Для обертки `rates__wrapper` даже нет стилей.
Зачем она нужна? Есть критерий [Д2](https://up.htmlacademy.ru/adaptive/23/criteries#d2), который по таким оберткам легко срезается. 

Но ладно критерий. Чем больше оберток — тем сложнее понимать твой код.

https://github.com/htmlacademy-adaptive/845199-pink-23/blob/9b36b3c1bd6e75a2dc5d880ded39fb6cb9e7c564/source/index.html#L185

2021-08-21 15:20 UTC, wrgraff commented on source/sass/blocks/rates.scss
> +  padding-top: 82px;
Почем паддинг, благодаря котором видно фон самого блока `rates` делается через `rates__list`?

2021-08-21 15:20 UTC, wrgraff commented on source/sass/blocks/rates.scss
> +    width: 832px;
Задай или ширину таблицы или ширину колонок. Не надо и то и другое делать. Один размер должен формировать другой.

https://github.com/htmlacademy-adaptive/845199-pink-23/blob/9b36b3c1bd6e75a2dc5d880ded39fb6cb9e7c564/source/sass/blocks/rates.scss#L47
https://github.com/htmlacademy-adaptive/845199-pink-23/blob/9b36b3c1bd6e75a2dc5d880ded39fb6cb9e7c564/source/sass/blocks/rates.scss#L54
https://github.com/htmlacademy-adaptive/845199-pink-23/blob/9b36b3c1bd6e75a2dc5d880ded39fb6cb9e7c564/source/sass/blocks/rates.scss#L59
https://github.com/htmlacademy-adaptive/845199-pink-23/blob/9b36b3c1bd6e75a2dc5d880ded39fb6cb9e7c564/source/sass/blocks/rates.scss#L64

2021-08-22 12:03 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +  position: absolute;
ok

2021-08-22 12:04 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +  left: 25;
Ок. Убрал

2021-08-22 12:04 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +  position: absolute;
Убрал

2021-08-22 12:06 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +    width: 100%;
Это начальная ошибка. Я потом уточнял у тебя в телеграме, и ты пояснил, что переопределять значение не нужно, если оно уже задано для меньшего размера. С этого момента я так не делал, но не переделал то, что делал до этого.
Я понял, и сейчас так не делаю.

2021-08-22 12:07 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +    top: 109;
Понял, да. Глупые ошибки. Исправляю.

2021-08-22 14:13 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +  align-items: center;
Исправил. Убрал флекс, добавил ссылкам кликабельный размер, выровнял

2021-08-22 14:22 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +  flex-direction: column;
убрал

2021-08-22 14:23 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +    position: relative;
Да, конечно. Поменял

2021-08-22 14:24 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +    min-height: 110px;
Убрал

2021-08-22 14:25 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +    display: flex;
Я уже понял. Мы это обсуждали, и я перестал дублировать записи. Это я просто забыл исправить.

2021-08-22 14:29 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +    justify-content: space-between;
Я забыл добавить паддинги для десктопа. Добавил Проверил по переполнению. Вроде бы работает как нужно.

2021-08-22 14:32 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  width: 100%;
Убрал

2021-08-22 14:53 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +.page-header__inner-wrapper {
Да, кнопку удобно центрировать. Сделал для десктопа

2021-08-22 14:55 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +    position: static;
Да, это после всяких экспериментов с абсолютами и релативами с выпадающим меню осталось. Забыл убрать. Поправил.

2021-08-22 15:12 UTC, dopamine-s commented on source/sass/blocks/main-nav.scss
> +    position: relative;
Подумал. Убрал вообще. Это осталось после экспериментов с абсолютами для меню

2021-08-23 00:16 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +}
Поменял

2021-08-23 00:16 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  background-size: object-fit;
Сделал

2021-08-23 00:16 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  flex-direction: column;
Убрал

2021-08-23 00:16 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  background-position: top;
Указал

2021-08-23 00:17 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +    min-height: 645px;
Сделал

2021-08-23 00:17 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  margin-top: 36px;
Изменил

2021-08-23 00:17 UTC, dopamine-s commented on source/index.html
> +        </section>
Посмотрю и применю, если хватит времени всё переделать

2021-08-23 00:18 UTC, dopamine-s commented on source/sass/blocks/app.scss
> +  min-height: 271px;
Понял, поправил

2021-08-23 00:18 UTC, dopamine-s commented on source/sass/blocks/app.scss
> +  justify-content: space-between;
Ну ведь понадобится? Убрал

2021-08-23 00:18 UTC, dopamine-s commented on source/sass/blocks/app.scss
> +  width: 280px;
Убрал

2021-08-23 00:18 UTC, dopamine-s commented on source/sass/global/variables.scss
> +$desktop: 960px;
Поменял

2021-08-23 00:18 UTC, dopamine-s commented on source/sass/blocks/mixins.scss
> +@mixin container {
Понял. Пока так.

2021-08-23 00:19 UTC, dopamine-s commented on source/index.html
> +          <div class="app-functions__list-bg-wrapper">
С фонами я слегка запутался. Их много. Насчет системности согласен. Если останется время, нужно переработать всё по твоим рекомендациям.

2021-08-23 03:43 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +  grid-row: 1 / 2;
Поправил

2021-08-23 03:43 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +.app-functions__list dt {
Убрал

2021-08-23 03:45 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +    background-repeat: no-repeat;
Убрал

2021-08-23 03:45 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +    min-height: 481px;
Убираю

2021-08-23 03:47 UTC, dopamine-s commented on source/sass/blocks/article.scss
> +    background-position: 0% 17px;
Убрал

2021-08-23 03:48 UTC, dopamine-s commented on source/sass/blocks/article.scss
> +  flex-direction: column;
Убрал

2021-08-23 03:48 UTC, dopamine-s commented on source/sass/blocks/article.scss
> +  flex-wrap: wrap;
Убрал флекс

2021-08-23 03:48 UTC, dopamine-s commented on source/sass/blocks/article.scss
> +  justify-content: space-between;
Убрал флекс

2021-08-23 03:50 UTC, dopamine-s commented on source/index.html
> +              </dd>
Поменял. С фоном не выходит. В целом, блок вроде бы теперь работает.

2021-08-23 05:19 UTC, dopamine-s commented on source/index.html
> +              </dd>
Сделал это чертов фон. С переполнением вопросы. Зачем вообще копировать блоками, разве это реальный сценарий? Если просто вставить текст в три раза больше, разве не так должно работать переполнение?

2021-08-23 05:22 UTC, dopamine-s commented on source/index.html
> +        <article class="page-main__article article">
Согласен, по тегам семантически неверно. Хотя название article в контексте названия раздела звучит нормально. Лучше не придумывается. Поменяю разметку на div.

2021-08-23 05:31 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +    z-index: 2;
Всё перекроил

2021-08-23 05:31 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +  min-height: 755px;
Поменял всё

2021-08-23 05:34 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +  background-position: 50% 110%;
Изменил

2021-08-23 05:49 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +  max-width: 280px;
Сделал

2021-08-23 05:49 UTC, dopamine-s commented on source/sass/blocks/app-functions.scss
> +    background-position: 0% 0%;
Убрал

2021-08-23 06:21 UTC, dopamine-s commented on source/index.html
> +          <div class="article__wrapper">
Убрал

2021-08-24 10:02 UTC, dopamine-s commented on source/index.html
> +              <div class="reviews__author-about">
Поменял

2021-08-24 10:05 UTC, dopamine-s commented on source/sass/blocks/social.scss
> +  justify-content: space-between;
Поправлю, когда дойдет до этого. Поставил wrap на всякий случай.

2021-08-24 10:05 UTC, dopamine-s commented on source/sass/blocks/social.scss
> +  min-width: 172px;
Убрал ширину

2021-08-24 10:09 UTC, dopamine-s commented on source/sass/blocks/site-list.scss
> +  padding-bottom: 25px;
Переделал... вроде бы лучше.

2021-08-24 10:10 UTC, dopamine-s commented on source/sass/blocks/page.scss
> +}
Переделал

2021-08-24 10:12 UTC, dopamine-s commented on source/sass/blocks/page-footer.scss
> +  display: inline-block;
Пока убрал. Сделаю в следующем разделе

2021-08-24 10:13 UTC, dopamine-s commented on source/sass/blocks/page-footer.scss
> +    min-height: 197px;
Убрал везде высоту. Выровняю в следующем разделе.

2021-08-24 10:15 UTC, dopamine-s commented on source/sass/blocks/rates.scss
> +    width: 832px;
Убрал общую ширину

2021-08-24 10:30 UTC, dopamine-s commented on source/index.html
> +          <div class="page-footer__logo-wrapper">
Предполагалось, что два логотипа будут выравниваться. Но ты сказал, что это один логотип, просто везде разный. А обертку я забыл убрать. Убираю.

2021-08-24 10:30 UTC, dopamine-s commented on source/index.html
> +        <div class="page-footer__low-bar">
Я уже понял...

2021-08-24 10:31 UTC, dopamine-s commented on source/index.html
> +        <div class="page-footer__low-bar">
Переделал

2021-08-24 10:34 UTC, dopamine-s commented on source/index.html
>                  </tr>
Это бред, согласен. Осталось после первоначальной разметки, я ориентировался на тренажер.

2021-08-24 10:59 UTC, dopamine-s commented on source/sass/blocks/rates.scss
> +  padding-top: 82px;
Поправил

2021-08-24 19:34 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    width: 100%;
Да, я так и подумал, но так как это косяк, надо подчистить эти моменты

2021-08-24 19:40 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    position: relative;
Ну, абсолюты какие-то понадобятся в итоге.
Но для модификаторов типа `--open` и `--close`

2021-08-24 20:12 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    justify-content: space-between;
Так уже лучше.
Вообще, если там очень хочется добавить место про запас, то это можно, но скорее всего придется помудрить и сделать чуть иначе, чтобы места побольше было.

2021-08-24 21:17 UTC, wrgraff commented on source/sass/blocks/app.scss
> +  justify-content: space-between;
Нет, не понадобится, потому что через `justify-content: space-between;` сетку не построить **никогда**
Это может работать вспомогательно в очень редких случаях, когда нужно сделать довольно специфическую сетку.
В обычных случаях это _НЕ РАБОТАЕТ_ никогда, потому что 95% сеток имеют именно фиксированные отступы.

2021-08-24 21:24 UTC, wrgraff commented on source/sass/blocks/app-functions.scss
> +.app-functions__list-wrapper {
Почему не повесить это все на `app-functions__list`? Зачем дополнительная обертка?

2021-08-24 21:24 UTC, wrgraff commented on source/index.html
> +              </dd>
Нормальная ситуация копирования блоками.
В общем списке это был бы заголовок + параграфы. Параграфов может быть несколько. Не обязательно текст захотят поместить внутрь параграфа, это может быть отдельная мысль и, соответственно, отдельный абзац текста.
В твоей версии параграфов нет, соответственно я копирую в качестве абзаца описание

2021-08-24 21:30 UTC, wrgraff commented on source/index.html
> +        <div class="page-main__article article">
Да почему то `article`, то `div`?
Все крупные разделы были `section`. Чем этот особенный такой?

2021-08-24 21:30 UTC, wrgraff commented on source/sass/blocks/social.scss
> +  justify-content: space-between;
Надо либо делать нормально, либо не делать вообще.
Зачем делать через одно место, но временно?

2021-08-24 22:27 UTC, wrgraff approved these changes

2021-08-24 22:27 UTC, wrgraff commented on source/sass/blocks/article.scss
>      margin-left: 310px;
https://github.com/htmlacademy-adaptive/845199-pink-23/blob/def45ee1a89d5688dcfe8b2f7018314fd305ce76/source/sass/blocks/article.scss#L28

https://github.com/htmlacademy-adaptive/845199-pink-23/blob/def45ee1a89d5688dcfe8b2f7018314fd305ce76/source/sass/blocks/article.scss#L44

https://github.com/htmlacademy-adaptive/845199-pink-23/blob/def45ee1a89d5688dcfe8b2f7018314fd305ce76/source/sass/blocks/article.scss#L62

Можно же всему блоку задать внутренний отступ под картинку.
Не придется каждый элемент двигать. И новые можно добавить в будущем без проблем. Или величину отступа поменять всего один раз (в том числе на десктопе)

2021-08-24 22:27 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  margin-top: -90px;
Что-то не очень я понял, зачем тут отступ этот.
Вообще, там как-то странно все работает. Паддинг в `.page-header__content-wrapper--main` влияет на размер фоновой картинки...

Переделал бы лучше по примеру моего видео хэдер. С ним работать будет попроще.
Хотя бы статичную версию пока что. Это не должно много прям времени занять. Ролик час. Медленный час лайвкодинга без подготовки.

2021-08-24 22:27 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  width: 320px;
А чего контейнер не миксуешь?

2021-08-24 22:28 UTC, merged

2021-08-25 12:18 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
>    height: 66px;
Контейнер, да. Поставил

2021-08-25 12:30 UTC, dopamine-s commented on source/sass/blocks/app.scss
> +  padding-bottom: 38px;
Да. Перенес на app. Теперь padding у всей секции

2021-08-25 12:32 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> -    min-height: 645px;
Убрал. Это невнимательность.

2021-08-25 12:33 UTC, dopamine-s commented on source/index.html
> +        <div class="page-main__article article">
Да, действительно.  Поменял