Module5 task1
htmlacademy-adaptive/845199-pink-23 pull request #8
Opened 2021-09-03 23:53 UTC by dopamine-s

2021-09-04 20:00 UTC, wrgraff requested changes

2021-09-04 20:00 UTC, wrgraff commented on source/sass/global/variables.scss
> +$gray-500-transparent-6: rgba(40, 54, 69, 0.6);
Я разве не писал, что можно прямо на месте применять цвет так:
`rgba($gray-500, 0.6);`
И не заводить для каждого `$gray-500` отдельную переменную цвета. Цвет то один же.

2021-09-05 22:09 UTC, dopamine-s commented on source/catalog.html
> +        <div class="page-header__top-bar page-header__top-bar--opened">
ОК

2021-09-05 22:10 UTC, dopamine-s commented on source/form.html
> +        <div class="page-header__top-bar page-header__top-bar--closed">
ОК

2021-09-05 22:11 UTC, dopamine-s commented on source/index.html
> +        <div class="page-header__top-bar page-header__top-bar--opened">
OK

2021-09-05 22:13 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  background-color: inherit;
OK

2021-09-05 22:25 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  }
Исправил

2021-09-05 22:43 UTC, dopamine-s commented on source/sass/blocks/contacts.scss
> +    padding-top: 6.5%;
OK

2021-09-05 23:02 UTC, dopamine-s commented on source/sass/blocks/contacts.scss
> +  }
Сделал

2021-09-05 23:15 UTC, dopamine-s commented on source/sass/blocks/page-main.scss
> +    background: linear-gradient(-5deg, $gray-300 49.5%, $white 50%);
Это не из-за полпроцента. А какие-то конкретные значения. Поставил другое - всё нормально.

2021-09-05 23:17 UTC, dopamine-s commented on source/sass/blocks/page-main.scss
> +    height: 161%;
Я наоборот убрал лишнюю обертку, на которой фон держался и всё. Мне кажется, так оптимальней.

2021-09-05 23:18 UTC, dopamine-s commented on source/sass/blocks/rates.scss
> +    border-right: 23px solid transparent;
Буду иметь в виду. Пока так оставлю. Зря что ли старался?)

2021-09-05 23:20 UTC, dopamine-s commented on source/sass/blocks/rates.scss
>  .rates {
Посмотрю. Пока оставлю, времени мало. С таблицей я долго мучался

2021-09-05 23:45 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +    height: 161%;
То, что я предлагаю, не требует никакой обертки лишней, речь идёт о работе только с этим элементом и его псевдоэлементом.

Твое решение не оптимальней. Оно плохо работает с переполнением и содержит в себе непонятные значения, не соответствующие параметрам из макета и привязанные к переменному значению.
С таким кодом будет трудно работать: ни другой разработчик, ни ты сам через несколько недель.

2021-09-05 23:48 UTC, wrgraff commented on source/sass/blocks/rates.scss
> +    border-right: 23px solid transparent;
Получается, что зря, потому что это сложное решение, которое не работает очевидным образом.
Его стоит переписать, учитывая что это не так уж сложно

2021-09-06 00:13 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  height: 23px;
Поправил

2021-09-06 00:13 UTC, dopamine-s commented on source/sass/blocks/page-header.scss
> +  &::before {
Поправил

2021-09-06 00:19 UTC, dopamine-s commented on source/sass/blocks/contacts.scss
> +    background: linear-gradient(to right top, transparent 49.5%, $white 50%) left / 50.02% 100% no-repeat,
Если будет время, я обязательно вернусь к этому вопросу, как и к ряду других. Пока хочу просто рабочий вариант.

2021-09-06 00:19 UTC, dopamine-s commented on source/sass/blocks/platform-list.scss
> +  height: 56px;
Если будет время, я обязательно вернусь к этому вопросу, как и к ряду других. Пока хочу просто рабочий вариант.

2021-09-06 18:35 UTC, wrgraff commented on source/sass/blocks/rates.scss
> +    border-right: 23px solid transparent;
Но вообще, любая работа идет в копилку опыта

2021-09-06 18:42 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +    background: linear-gradient(-5deg, $gray-300 49.5%, $white 50%);
Это из-за _разницы_ в пол процента:
`50% - 49.5% = 0.5%`
Получается градиент размером в пол процента. Это много и поэтому граница размыта

2021-09-06 18:43 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +    background: linear-gradient(-5deg, $gray-300 49.5%, $white 50%);
Когда ставишь 1 к 1, то получается "лесенка". Это из-за того, что в фоне плохое сглаживание (точнее, его там нет). И мы делаем его самостоятельно, оставляя небольшой зазор для градиента.
Но пол процента — это много. Вот о чем речь.

2021-09-06 18:45 UTC, wrgraff approved these changes
Времени достаточно для того, чтобы делать хорошие решения.
Факт того, что "успел защититься" никак не поможет затем при поиске работы, если код будет плох.

2021-09-06 18:45 UTC, merged

2021-09-06 22:54 UTC, dopamine-s commented on source/sass/blocks/rates.scss
> +    border-right: 23px solid transparent;
ОК

2021-09-06 23:57 UTC, dopamine-s commented on source/sass/blocks/page-main.scss
> +    height: 161%;
Обертка лишняя потребуется обязательно. Потому что списку фон не задать. Список центрован. И фон обрежется. И всей секции фон не задать. Потому что тогда псевдоэлемент не будет видно. А если его вынести наверх слоем, то уже текст будет снизу. 
получается, нужно опять вводить обертку для серого фона